In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_wine
wine=load_wine()

In [2]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [38]:
from sklearn.preprocessing import MinMaxScaler
df=MinMaxScaler().fit_transform(wine.data)

In [45]:
df=pd.DataFrame(data=df, columns=wine.feature_names)
df['target']=wine.target
df.isnull().values.any()

False

In [50]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('target', axis=1), df['target'], test_size=0.2)

In [51]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB().fit(X_train,y_train)

In [52]:
model.score(X_test,y_test)

0.9166666666666666

In [53]:
from sklearn.naive_bayes import MultinomialNB
model_Mn=MultinomialNB().fit(X_train,y_train)

In [54]:
model_Mn.score(X_test,y_test)

0.9722222222222222

In [56]:
from sklearn.model_selection import cross_val_score
CV_G=cross_val_score(GaussianNB(), X_train, y_train, cv=3)
CV_Mn=cross_val_score(MultinomialNB(), X_train, y_train, cv=3)

display(CV_G, CV_Mn)

array([0.95833333, 0.9787234 , 1.        ])

array([0.95833333, 0.93617021, 0.93617021])

Multinomial is Better than Gaussian

In [58]:
model_Mn.predict(X_test[0:10])

array([2, 0, 0, 2, 1, 1, 1, 2, 0, 0])

In [59]:
model.predict_proba(X_test[0:10])

array([[3.11576838e-19, 4.14522849e-11, 1.00000000e+00],
       [9.99997679e-01, 2.32105936e-06, 1.95282955e-33],
       [9.99971798e-01, 2.82020664e-05, 2.81949486e-19],
       [1.73520058e-19, 1.00206604e-11, 1.00000000e+00],
       [1.26040745e-06, 9.99998740e-01, 1.13033073e-25],
       [3.46885738e-08, 9.99999965e-01, 1.84439015e-22],
       [1.17792222e-01, 8.82207778e-01, 5.21039966e-20],
       [3.53861939e-24, 2.68435365e-09, 9.99999997e-01],
       [1.00000000e+00, 4.65022284e-12, 2.20735234e-39],
       [3.54110835e-10, 1.00000000e+00, 2.72514717e-20]])